core/urls.py
from django.urls import path

from .views import home, create_post, like_post, comment_on_post, like_comment, reply_comment, delete_comment, delete_reply_comment, post_detail, add_friend, accept_friend_request, reject_friend_request, unfriend, inbox, inbox_detail, block_user

app_name = 'core'

urlpatterns = [
    path('',home, name='home'),
    path('post/<slug:slug>/',post_detail, name='post_detail'),
    
    # chat
    path("core/inbox", inbox, name="inbox"),
    path("core/inbox/<username>", inbox_detail, name="inbox_detail"),
    
    # Ajax urls
    path('create_post/',create_post, name='create_post'),
    path('like_post/',like_post, name='like_post'),
    path('comment_on_post/',comment_on_post, name='comment_on_post'),
    path('like_comment/',like_comment, name='like_comment'),
    path('reply_comment/',reply_comment, name='reply_comment'),
    path('delete_comment/',delete_comment, name='delete_comment'),
    path('delete_reply_comment/',delete_reply_comment, name='delete_reply_comment'),
    path('add_friend/',add_friend , name='add_friend'),
    path('accept_friend_request/',accept_friend_request , name='accept_friend_request'),
    path('reject_friend_request/',reject_friend_request , name='reject_friend_request'),
    path('unfriend/',unfriend , name='unfriend'),
    path('block_user/',block_user , name='block_user'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from core.routing import websocket_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('user/',include('userauths.urls')),
    
    # web sokect
    path('ws/', include(websocket_urlpatterns)),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.shortcuts import render, redirect
from django.utils.text import slugify
from django.http import JsonResponse
from django.utils.timesince import timesince
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.db.models import OuterRef, Subquery, Q, F



import shortuuid
from .models import Post, Comment, ReplyComment, Friend, FriendRequest, Notification, ChatMessage
from userauths.models import User



# Notifications Keys
noti_new_like = "New Like"
noti_new_follower = "New Follower"
noti_friend_request = "Friend Request"
noti_new_comment = "New Comment"
noti_comment_liked = "Comment Liked"
noti_comment_replied = "Comment Replied"
noti_friend_request_accepted = "Friend Request Accepted"


@login_required
def home(request):
    posts = Post.objects.filter(active=True, visibility='Everyone').order_by("-id")   # .order_by("-id") ----->>show modern post
    context = {
        "posts":posts
    }
    return render(request,'core/home.html', context)


@login_required
def post_detail(request, slug):
    post = Post.objects.get(slug=slug, active=True, visibility='Everyone')   # id = request.GET['id]          post = Post.objects.get(id=id)
    context = {
        "post":post
    }
    return render(request, 'core/post_detail.html', context)


def send_notification(user, sender, post, comment, notification_type):
    notification = Notification.objects.create(
        user=user,
        sender=sender,
        post=post,
        comment=comment,
        notification_type=notification_type,
    )
    return notification


@csrf_exempt
def create_post(request):
    if request.method == "POST":
        title = request.POST.get('post-caption')
        visibility = request.POST.get('visibility')
        image = request.FILES.get('post-thumbnail')
        

        uuid_key = shortuuid.uuid()
        uniqueid = uuid_key[:4]


        if title and image:
            post = Post(
                title=title,
                image=image,
                visibility=visibility,
                user=request.user,
                slug=slugify(title) + '-' + str(uniqueid.lower()),
            )
            post.save()

            return JsonResponse({'post' :{
                'title':post.title,
                "image":post.image.url,
                "full_name":post.user.profile.full_name,
                "profile_image":post.user.profile.image.url,
                'date':timesince(post.date),
                'id':post.id,
            }})
        else:
            return JsonResponse({'error': 'Image or titile dose not exists'})
        
    return JsonResponse({'data':'sent'})



def like_post(request):
    id = request.GET['id']
    post = Post.objects.get(id=id)
    user = request.user
    bool = False

    if user in post.likes.all():
        post.likes.remove(user)
        bool = False
    else:
        post.likes.add(user)
        bool = True
        
        if post.user != request.user:
            send_notification(post.user, user, post, None, noti_new_like)

    data = {
        'bool':bool,
        'likes':post.likes.all().count(),
    }

    return JsonResponse({'data':data})



def comment_on_post(request):
    id = request.GET['id']
    comment = request.GET['comment']
    post = Post.objects.get(id=id)
    Comment_count = Comment.objects.filter(post=post).count()
    user = request.user

    new_comment = Comment.objects.create(
        post=post,
        comment=comment,
        user=user,
    )
    
    if new_comment.user != post.user:
        send_notification(post.user, user, post, new_comment, noti_new_like)

    data = {
        'bool' : True,
        'comment' : new_comment.comment,
        "profile_image":new_comment.user.profile.image.url,
        'date' : timesince(new_comment.date),
        'comment_id' : new_comment.id,
        'post_id' : new_comment.post.id,
        'Comment_count' : Comment_count + int(1),
    }

    return JsonResponse({'data':data})


def like_comment(request):
    id = request.GET['id']
    comment = Comment.objects.get(id=id)   # comment = Comment.object.first()
    user = request.user
    bool= False

    if user in comment.likes.all():
        comment.likes.remove(user)
        bool = False
    else:
        comment.likes.add(user)
        bool = True
        
        if comment.user != user:
            send_notification(comment.user, user, comment.post, comment, noti_comment_liked)

    data = {
        'bool':bool,
        'likes' :comment.likes.all().count(),
    }

    return JsonResponse({'data':data})


def reply_comment(request):
    id = request.GET['id']
    reply = request.GET['reply']

    comment = Comment.objects.get(id=id)
    user = request.user

    new_reply = ReplyComment.objects.create(
        comment=comment,
        reply=reply,
        user=user,
    )
    
    if comment.user != user:
        send_notification(comment.user, user, comment.post, comment, noti_comment_replied)

    data = {
        'bool': True,
        'reply': new_reply.reply,
        'profile_image': new_reply.user.profile.image.url,
        'date': timesince(new_reply.date),
        'reply_id': new_reply.id,
        'post_id': new_reply.comment.post.id,
    }

    return JsonResponse({'data':data})



def delete_comment(request):
    id = request.GET['id']
    comment = Comment.objects.get(id=id)
    comment.delete()

    data = {
        'bool' : True,
    }

    return JsonResponse({'data':data})


def delete_reply_comment(request):
    id = request.GET['id']
    reply = ReplyComment.objects.get(id=id)
    reply.delete()
    
    data = {
        'bool' : True,
    }
    
    return JsonResponse({'data':data})



def add_friend(request):
    sender = request.user
    receiver_id = request.GET['id']
    bool = False
    
    if sender.id == int(receiver_id):
        return JsonResponse({'error':'You cannot send a friend request to yourself'})
    
    receiver = User.objects.get(id=receiver_id)
    
    try:
        friend_request = FriendRequest.objects.get(sender=sender, receiver=receiver)
        if friend_request:
            friend_request.delete()
        bool=False
        return JsonResponse({'error':'Cancelled', 'bool':bool})

    except FriendRequest.DoesNotExist:
        friend_request = FriendRequest(sender=sender, receiver=receiver)
        friend_request.save()
        bool = True
        
        
        send_notification(receiver, sender, None, None, noti_friend_request)
            
        return JsonResponse({'success':'Sent', 'bool':bool})


def accept_friend_request(request):
    id = request.GET['id']
    
    receiver = request.user
    sender = User.objects.get(id=id)
    
    friend_request = FriendRequest.objects.filter(receiver=receiver, sender=sender).first()
    
    receiver.profile.friends.add(sender)
    sender.profile.friends.add(receiver)
    
    friend_request.delete()
    
    send_notification(sender, receiver, None, None, noti_friend_request_accepted)

    
    data = {
        'message' : 'Accepted',
        'bool' : True,
    }
    return JsonResponse({"data":data})


def reject_friend_request(request):
    id = request.GET['id']
    
    receiver = request.user
    sender = User.objects.get(id=id)
    
    friend_reject = FriendRequest.objects.filter(receiver=receiver, sender=sender).first()    
    friend_reject.delete()
    
    data = {
        'message' : 'Rejected',
        'bool' : True,
    }
    return JsonResponse({"data":data})


def unfriend(request):
    sender = request.user
    friend_id = request.GET['id']
    bool = False
    
    if sender.id == int(friend_id):
        return JsonResponse({"error":"You cannot unfriend yourself, wait a minute how did you even send yourself a friend request?"})
    
    my_friend = User.objects.get(id=friend_id)
    
    if my_friend in sender.profile.friends.all():
        sender.profile.friends.remove(my_friend)
        my_friend.profile.friends.remove(sender)
        bool = True
        return JsonResponse({"success":"Unfriend Successfully", "bool":bool})



@login_required
def inbox(request):
    user_id = request.user.id  # Use request.user.id instead of request.user

    chat_message = ChatMessage.objects.filter(
        id__in=Subquery(
            ChatMessage.objects.filter(
                Q(sender=user_id) | Q(receiver=user_id)
            ).distinct().order_by('sender', 'receiver', '-id').values('id')[:1]
        )
    ).order_by("-id")
    
    context = {
        'chat_message': chat_message,
    }
    return render(request, 'chat/inbox.html', context)


@login_required
def inbox_detail(request, username):
    user_id = request.user.id  # Use request.user.id instead of request.user

    message_list = ChatMessage.objects.filter(
        id__in=Subquery(
            ChatMessage.objects.filter(
                Q(sender=user_id) | Q(receiver=user_id)
            ).distinct().order_by('sender', 'receiver', '-id').values('id')[:1]
        )
    ).order_by("-id")
    
    sender = request.user
    receiver = User.objects.get(username=username)  # Use User instead of user
    receiver_detail = User.objects.get(username=username)  # Use User instead of user
    
    message_detail = ChatMessage.objects.filter(
        Q(sender=sender, receiver=receiver) | Q(sender=receiver, receiver=sender)
    ).order_by("date")
    
    message_detail.update(is_read=True)
    
    if message_detail:
        r = message_detail.first()
        receiver = User.objects.get(username=r.receiver)
    else:
        receiver = User.objects.get(username=username)
    
    context = {
        'message_detail': message_detail,
        "receiver": receiver, 
        "sender": sender,
        "receiver_detail": receiver_detail,
        "message_list": message_list,
    }
    return render(request, 'chat/inbox_detail.html', context)
        
        
def block_user(request):
    id = request.GET['id']
    user = request.user

core/templates/chat/inbox_detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}


    <body class="is_message">


        <!-- Main Contents -->
        <div class="main_content">

                <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

                <div class="messages-container">
                    <div class="messages-container-inner">


                        <div class="messages-inbox">
                            <div class="messages-headline">
                                <div class="input-with-icon" hidden>
                                    <input id="autocomplete-input" type="text" placeholder="Search">
                                    <i class="icon-material-outline-search"></i>
                                </div>
                                <h2 class="text-2xl font-semibold">Chats</h2>
                                <span class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></span>
                            </div>
                            <div class="messages-inbox-inner" data-simplebar>
                                <ul>
                                    {% for message in message_list %}
                                        {% if request.user == message.sender %}
                                            <li>
                                                <a href="{% url 'core:inbox_detail' message.receiver.username %}">
                                                    <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{message.receiver.profile.image.url}}" alt=""></div>

                                                    <div class="message-by">
                                                        <div class="message-by-headline">
                                                            <h5>{{message.receiver.profile.full_name}}</h5>
                                                            <!-- <span style="font-size: 15px;"><small>{{message.date|timesince}} ago</small></span> -->
                                                        </div>
                                                        <p>{{message.message}}</p>
                                                    </div>
                                                </a>
                                            </li>
                                        {% endif %}

                                        {% if request.user == message.receiver %}
                                            <li>
                                                <a href="{% url 'core:inbox_detail' message.sender.username %}">

                                                    <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{message.sender.profile.image.url}}" alt=""></div>

                                                    <div class="message-by">
                                                        <div class="message-by-headline">
                                                            <h5>{{message.sender.profile.full_name}}</h5>
                                                            <!-- <span style="font-size: 14px;"><small>{{message.date|timesince}} ago</small></span> -->
                                                        </div>
                                                        <p>{{message.message}}</p>
                                                    </div>
                                                </a>
                                            </li>
                                        {% endif %} 

                                    {% empty %}
                                        <li>
                                            <a href="#">
                                                <div class="message-by">
                                                    <div class="message-by-headline">
                                                        <h5>No messages yet</h5>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                    {% endfor %}


                                </ul>
                            </div>
                        </div>


                        <div class="message-content">

                            <div class="messages-headline">
                                <div class="flex">
                                    <img class="mr-1" src="{{ receiver_detail.profile.image.url }}" style="width: 40px; height: 40px; object-fit: cover; border-radius: 50%;" alt="">
                                    <h4 class="ml-1"> {{ receiver_detail.profile.full_name|title }} </h4>
                                </div>
                                {% if receiver_detail in request.user.profile.friends.all %}
                                    <a href="#" id="block-user-btn" data-block-user="{{receiver_detail.id}}" class="message-action text-red-500 "><i class="fas fa-ban"></i> <span class="md:inline hidden block-text{{receiver_detail.id}}" > Block {{ receiver_detail.profile.full_name|title }}</span> </a>
                                {% endif %}
                            
                            </div>
    
                            <div class="message-content-scrolbar" data-simplebar>
    
                                <!-- Message Content Inner -->
                                <div class="message-content-inner chat_container">
    


                                    {% for message in message_detail %}
                                        {% if message.sender == request.user %}
                                            <div class="message-bubble me">
                                                <div class="message-bubble-inner">
                                                    <div class="message-avatar"><img src="{{message.sender.profile.image.url}}" alt=""></div>
                                                    <div class="message-text">
                                                        <p>{{message.message}}</p>
                                                        <p style="font-size: 12px; color: rgb(199, 171, 171)">{{message.date | timesince}} ago</p>
                                                    </div>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                        {% else %}
                                            <div class="message-bubble">
                                                <div class="message-bubble-inner">
                                                    <div class="message-avatar"><img src="{{message.sender.profile.image.url}}" alt=""></div>
                                                    <div class="message-text">
                                                        <p>{{message.message}}</p>
                                                        <p style="font-size: 12px; color: gray">{{message.date | timesince}} ago</p>
                                                    </div>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                    <div id="chat-messages"></div>

                                </div>
                                <!-- Message Content Inner / End -->
    
                                <!-- Reply Area -->
                                <div class="message-reply">
                                    <textarea id="chat-input" cols="1" rows="1" placeholder="Write Message"></textarea>
                                    <button id="send-btn" class="button ripple-effect" >Send</button>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

        <script>
            var receiver_id = "{{ receiver.username }}"; 
            var logged_in = "{{ request.user.username }}";
        
            const pathname = window.location.pathname;
            console.log(pathname);
        
            const parts = pathname.split("/");
            const username = parts[parts.length - 1];
            console.log(username);
        
            var receiver = (receiver_id === logged_in) ? receiver_id : username;
        
            var socket = new WebSocket("ws://" + window.location.host + "/ws/chat/" + receiver + "/");
        
            socket.onopen = function(){
                console.log("WebSocket connection established.");
            }
        
            socket.onmessage = function(event){
                var data = JSON.parse(event.data);
                var message = data.message;
                var sender = data.sender;
                var profile_image = data.profile_image;
                var receiver = data.receiver;
        
                if(sender === "{{ request.user.username }}"){
                    var chatMessage = '<div class="message-bubble me">';
                    chatMessage += '<div class="message-bubble-inner">';
                    chatMessage += '<div class="message-avatar"><img src="' + profile_image + '" alt=""></div>';
                    chatMessage += '<div class="message-text">';
                    chatMessage += '<p>' + message + '</p>';
                    chatMessage += '</div>';
                    chatMessage += '</div>';
                    chatMessage += '<div class="clearfix"></div>';
                    chatMessage += '</div>';
                    $("#chat-messages").append(chatMessage); // corrected append method name
                } else {
                    var chatMessage = '<div class="message-bubble">';
                    chatMessage += '<div class="message-bubble-inner">';
                    chatMessage += '<div class="message-avatar"><img src="' + profile_image + '" alt=""></div>';
                    chatMessage += '<div class="message-text">';
                    chatMessage += '<p>' + message + '</p>';
                    chatMessage += '</div>';
                    chatMessage += '</div>';
                    chatMessage += '<div class="clearfix"></div>';
                    chatMessage += '</div>';
                    $("#chat-messages").append(chatMessage); // corrected append method name
                }
            }
        
            socket.onclose = function(){
                console.log("WebSocket connection closed..");
            }
        
        
            // send message
            $("#send-btn").on("click", function(){
                var input = $("#chat-input");
                var message = input.val();
                var sender = "{{ request.user.username }}";
                var data = {
                    'message': message,
                    'sender': sender,
                    'receiver': username,
                };
                socket.send(JSON.stringify(data));
                input.val("");
                var sendButton = $('#send-btn');
                sendButton.prop('disabled', true);
                $(".chat_container").scrollTop(100000000000);
                console.log("Message sent");
            });

            // Block User
            $(document).on("click", "#block-user-btn", function(){
                let id = $(this).attr("data-block-user");
                console.log(id);
            
                $.ajax({
                    url: "/block_user/",
                    dataType: "json",
                    beforeSend: function(){
                        $("#block-user-btn").html("<i class='fas fa-check-circle'></i> User Blocked successfully.");
                    },
                    data: {
                        "id": id,
                    },
                    success: function(response){
                        console.log(response);
                        $(".block-text").html("<i class='fas fa-check-circle'></i> User Blocked successfully.");
                    }
                });
            });
            
            
        
        </script>
        
        
        


    

    </body>

{% endblock body %}